twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_3_layout.html.twig', 'form/fields.html.twig']
    globals:
        captchaKey: '%env(CAPTCHA_KEY)%'
when@test:
    twig:
        strict_variables: true
