controllers:
    prefix:
        en: /
        ru: /ru
    resource: ../src/Controller/*
    exclude: ../src/Controller/Admin
    type: attribute

admin:
    prefix: /admin
    resource: ../src/Controller/Admin
    type: attribute

lucky_show:
    path: /product/show/{id}
    controller: App\Controller\LuckyController::show
    requirements:
        id: \d+

app_logout:
    path: /logout
